---
- name: Ghost
  hosts: all
  remote_user: ansible
  become: true

  gather_facts: true
  any_errors_fatal: true

  pre_tasks:

    - name: Ghost | Pinging hosts.
      action: ping

  roles:
    - ubzyhd.ghost
