---
- name: Ghost | Running pre-setup of packages
  include_tasks: "packages-{{ ansible_os_family }}.yml"

- name: Ghost | Install & Configuring Ghost
  include_tasks: "mariadb.yml"

- name: Ghost | Configuring firewall
  include_tasks: "ufw.yml"
  when: not ci_build_testing
