---
# Include variables and define needed variables.
- name: packages-{{ ansible_os_family }} | Include OS-specific variables.
  include_vars: "vars-{{ ansible_os_family }}.yml"

# Update the server
- name: packages-{{ ansible_os_family }} | Updating Server
  apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    purge: true

- name: packages-{{ ansible_os_family }} | Installing Required Packages
  apt:
    name: "{{ required_packages }}"
    update_cache: true
    install-recommends: false
    state: present
