---
- name: Create database user with name 'bob' and password '12345' with all database privileges
  mysql_user:
    name: bob
    password: "12345"
    priv: '*.*:ALL'
    state: present

- name: Create a new database with name 'bobdata'
  mysql_db:
    name: bobdata
    login_host: "192.168.2.6"
    state: present
